#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Wswl.MUI.Resource", IsApplication=true)]

namespace Wswl.MUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int isOpen = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int shape = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int themeColor = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int deviceOffline = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int header_br = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int home_alarm = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_arrow_right = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_device = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_device_off = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_devices_white = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_gateway = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_home_white = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_menu_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_more_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_news_white = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_outline = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_search_white = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_setting = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_shopping = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_un_warning = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_user = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_warning = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int image_user = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int logo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int selectedTab = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int tab_bg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tab_icon_home = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int tab_state = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int unselectedTab = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int app_message_content = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int app_message_image = 2130968578;
			
			// aapt resource value: 0x7f04001a
			public const int btn_home_online_devices = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int btn_home_online_user = 2130968603;
			
			// aapt resource value: 0x7f04002a
			public const int btn_login_link = 2130968618;
			
			// aapt resource value: 0x7f040028
			public const int btn_login_login = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int btn_login_register = 2130968617;
			
			// aapt resource value: 0x7f040049
			public const int btn_reg_back = 2130968649;
			
			// aapt resource value: 0x7f040048
			public const int btn_reg_register = 2130968648;
			
			// aapt resource value: 0x7f040042
			public const int button10_devices = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int button11_devices = 2130968643;
			
			// aapt resource value: 0x7f040041
			public const int button12_devices = 2130968641;
			
			// aapt resource value: 0x7f040038
			public const int button1_devices = 2130968632;
			
			// aapt resource value: 0x7f040030
			public const int button1_manages = 2130968624;
			
			// aapt resource value: 0x7f040039
			public const int button2_devices = 2130968633;
			
			// aapt resource value: 0x7f040031
			public const int button2_manages = 2130968625;
			
			// aapt resource value: 0x7f04003a
			public const int button3_devices = 2130968634;
			
			// aapt resource value: 0x7f040032
			public const int button3_manages = 2130968626;
			
			// aapt resource value: 0x7f04003b
			public const int button4_devices = 2130968635;
			
			// aapt resource value: 0x7f040033
			public const int button4_manages = 2130968627;
			
			// aapt resource value: 0x7f04003c
			public const int button5_devices = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int button6_devices = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int button7_devices = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int button8_devices = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int button9_devices = 2130968640;
			
			// aapt resource value: 0x7f040001
			public const int circle = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int deveces_content = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int devices_image_br = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int devices_menu = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int home_image_br = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int home_layout_content = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int home_menu_gateway = 2130968586;
			
			// aapt resource value: 0x7f040015
			public const int img_home_icon_setting = 2130968597;
			
			// aapt resource value: 0x7f040013
			public const int img_home_icon_user = 2130968595;
			
			// aapt resource value: 0x7f040017
			public const int img_home_icon_warning = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int img_home_user = 2130968592;
			
			// aapt resource value: 0x7f040025
			public const int img_login_logo = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int k0203_layout_content = 2130968612;
			
			// aapt resource value: 0x7f040021
			public const int k02_info = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int k02_menu = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int k02_title = 2130968608;
			
			// aapt resource value: 0x7f04001e
			public const int layout_home_devices = 2130968606;
			
			// aapt resource value: 0x7f040006
			public const int lbl_devices_info = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int lbl_devices_title = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int lbl_home_alarm = 2130968588;
			
			// aapt resource value: 0x7f04001d
			public const int lbl_home_devices = 2130968605;
			
			// aapt resource value: 0x7f04000b
			public const int lbl_home_gateway = 2130968587;
			
			// aapt resource value: 0x7f040014
			public const int lbl_home_userName = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int lbl_home_warning = 2130968600;
			
			// aapt resource value: 0x7f04002d
			public const int lbl_manages_info = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int lbl_manages_title = 2130968620;
			
			// aapt resource value: 0x7f040036
			public const int lbl_news_info = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int lbl_news_title = 2130968629;
			
			// aapt resource value: 0x7f040044
			public const int lbl_reg_title = 2130968644;
			
			// aapt resource value: 0x7f040011
			public const int linearLayout1 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int linearLayout2 = 2130968594;
			
			// aapt resource value: 0x7f040016
			public const int linearLayout3 = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int linearLayout4 = 2130968601;
			
			// aapt resource value: 0x7f04001c
			public const int linearLayout5 = 2130968604;
			
			// aapt resource value: 0x7f04002e
			public const int manages_image_br = 2130968622;
			
			// aapt resource value: 0x7f04002b
			public const int manages_menu = 2130968619;
			
			// aapt resource value: 0x7f040022
			public const int news_image_br = 2130968610;
			
			// aapt resource value: 0x7f040034
			public const int news_menu = 2130968628;
			
			// aapt resource value: 0x7f040000
			public const int rect = 2130968576;
			
			// aapt resource value: 0x7f040037
			public const int scrollView1 = 2130968631;
			
			// aapt resource value: 0x7f040008
			public const int sv_devices = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int sv_home = 2130968590;
			
			// aapt resource value: 0x7f040023
			public const int sv_k02 = 2130968611;
			
			// aapt resource value: 0x7f04002f
			public const int sv_manages = 2130968623;
			
			// aapt resource value: 0x7f04004b
			public const int tabIcon = 2130968651;
			
			// aapt resource value: 0x7f04004a
			public const int tabLayout = 2130968650;
			
			// aapt resource value: 0x7f04004c
			public const int tabText = 2130968652;
			
			// aapt resource value: 0x7f040027
			public const int txt_login_password = 2130968615;
			
			// aapt resource value: 0x7f040026
			public const int txt_login_userName = 2130968614;
			
			// aapt resource value: 0x7f040047
			public const int txt_reg_confirmPassword = 2130968647;
			
			// aapt resource value: 0x7f040046
			public const int txt_reg_password = 2130968646;
			
			// aapt resource value: 0x7f040045
			public const int txt_reg_userName = 2130968645;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int app_message = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Devices = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Home = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int K0203 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Manages = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int News = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Register = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TabStyle = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int WswlAppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] slideswitch = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int slideswitch_isOpen = 1;
			
			// aapt resource value: 2
			public const int slideswitch_shape = 2;
			
			// aapt resource value: 0
			public const int slideswitch_themeColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
