#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Wswl.MUI.Resource", IsApplication=true)]

namespace Wswl.MUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_devicesl_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_home_white = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_more_white = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_news_white = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int selectedTab = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tab_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tab_icon_home = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tab_state = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int unselectedTab = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int app_message_content = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int app_message_image = 2131099648;
			
			// aapt resource value: 0x7f06000c
			public const int btn_login_link = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int btn_login_login = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int btn_login_register = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int btn_reg_back = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int btn_reg_register = 2131099665;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int img_login_logo = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int lbl_reg_title = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout2 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout3 = 2131099659;
			
			// aapt resource value: 0x7f060014
			public const int tabIcon = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int tabLayout = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int tabText = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int txt_login_password = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int txt_login_userName = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int txt_reg_confirmPassword = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int txt_reg_password = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int txt_reg_userName = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int app_message = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Register = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TabStyle = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int WswlAppTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
